import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("site-access", "routes/site-access.tsx"),
  route("about", "routes/about.tsx"),
  route("rally", "routes/rally.tsx"),
  route("login", "routes/login.tsx"),
  route("logout", "routes/logout.tsx"),
  route("registration", "routes/registration._index.tsx"),
  route("registration/success", "routes/registration.success.tsx"),
  route("dashboard", "routes/dashboard._index.tsx"),
  route("dashboard/rally-submission", "routes/dashboard.rally-submission.tsx"),
  route("zone/:zoneId", "routes/zone.$zoneId.tsx"),
  route("admin", "routes/admin._index.tsx"),
  route("admin/participants", "routes/admin.participants.tsx"),
  route("admin/participants/:participantId/submissions", "routes/admin.participants.$participantId.submissions.tsx"),
  route("admin/check-in", "routes/admin.check-in.tsx"),
  route("admin/submissions", "routes/admin.submissions.tsx"),
  route("admin/leaderboard", "routes/admin.leaderboard.tsx"),
  route("admin/settings", "routes/admin.settings.tsx"),
  route("admin/pending-scans", "routes/admin.pending-scans.tsx"),
  route("admin/zone-control", "routes/admin.zone-control.tsx"),
  route("admin/manual-scan", "routes/admin.manual-scan.tsx"),
  route("admin/event-markers", "routes/admin.event-markers.tsx"),
  route("live-map", "routes/live-map.tsx"),
  route("api/webhook", "routes/api.webhook.tsx"),
  route("api/shadow-recalculate", "routes/api.shadow-recalculate.tsx"),
  route("api/rally-submission", "routes/api.rally-submission.tsx"),
  route("api/qrcode", "routes/api.qrcode.tsx"),
  route("api/events/submit", "routes/api.events.submit.tsx"),
  route('check-in/:participantId', 'routes/check-in.$participantId.tsx'),
  route("certificates/:type", "routes/certificates.$type.tsx"),
  route("achievements", "routes/achievements.tsx"),
  route("gallery", "routes/gallery.tsx"),
  route("admin/gallery", "routes/admin.gallery.tsx"),
  route("admin/push-notifications", "routes/admin.push-notifications.tsx"),
  route("api/push-subscribe", "routes/api.push-subscribe.tsx"),
  route('api/rally-zones', 'routes/api.rally-zones.tsx'),
] satisfies RouteConfig;
