// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/rally": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/choice-points": {
    params: {};
  };
  "/rider-groups": {
    params: {};
  };
  "/leaderboard": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/events": {
    params: {};
  };
  "/admin/events/new": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/register" | "/login" | "/forgot-password" | "/profile" | "/logout" | "/rally" | "/dashboard" | "/choice-points" | "/rider-groups" | "/leaderboard" | "/admin" | "/admin/events" | "/admin/events/new";
  };
  "layouts/public.tsx": {
    id: "layouts/public";
    page: "/" | "/about" | "/register" | "/login" | "/forgot-password" | "/profile";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/forgot-password.tsx": {
    id: "routes/forgot-password";
    page: "/forgot-password";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/logout.ts": {
    id: "routes/logout";
    page: "/logout";
  };
  "layouts/protected.tsx": {
    id: "layouts/protected";
    page: "/rally" | "/dashboard" | "/choice-points" | "/rider-groups" | "/leaderboard";
  };
  "routes/rally.tsx": {
    id: "routes/rally";
    page: "/rally";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/choice-points.tsx": {
    id: "routes/choice-points";
    page: "/choice-points";
  };
  "routes/rider-groups.tsx": {
    id: "routes/rider-groups";
    page: "/rider-groups";
  };
  "routes/leaderboard.tsx": {
    id: "routes/leaderboard";
    page: "/leaderboard";
  };
  "layouts/admin.tsx": {
    id: "layouts/admin";
    page: "/admin" | "/admin/events" | "/admin/events/new";
  };
  "routes/admin._index.tsx": {
    id: "routes/admin._index";
    page: "/admin";
  };
  "routes/admin.events._index.tsx": {
    id: "routes/admin.events._index";
    page: "/admin/events";
  };
  "routes/admin.events.new.tsx": {
    id: "routes/admin.events.new";
    page: "/admin/events/new";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "layouts/public": typeof import("./app/layouts/public.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/forgot-password": typeof import("./app/routes/forgot-password.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/logout": typeof import("./app/routes/logout.ts");
  "layouts/protected": typeof import("./app/layouts/protected.tsx");
  "routes/rally": typeof import("./app/routes/rally.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/choice-points": typeof import("./app/routes/choice-points.tsx");
  "routes/rider-groups": typeof import("./app/routes/rider-groups.tsx");
  "routes/leaderboard": typeof import("./app/routes/leaderboard.tsx");
  "layouts/admin": typeof import("./app/layouts/admin.tsx");
  "routes/admin._index": typeof import("./app/routes/admin._index.tsx");
  "routes/admin.events._index": typeof import("./app/routes/admin.events._index.tsx");
  "routes/admin.events.new": typeof import("./app/routes/admin.events.new.tsx");
};